### ISSUE TITLE
App crashes when launching

### ISSUE THREAD

**Issue by Pinsho** [josh-seagrave/EasyCPDLC#64]
App is not opening when launching... this is what I get in the Windows Event Viewer:

Source: .NET Runtime
ID: 1026
Application: EasyCPDLC.exe
CoreCLR Version: 6.0.2023.32017
.NET Version: 6.0.20
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at EasyCPDLC.MainForm..ctor()
   at EasyCPDLC.Program.Main()

Source: Application Error
ID: 1000
Faulting Application Name: EasyCPDLC.exe, Version: 0.2.0.0, Time Stamp: 0x62571213
Faulting Module Name: KERNELBASE.dll, Version: 10.0.19041.3155, Timestamp: 0xbf300201
Exception Code: 0xe0434352
Error Offset: 0x000000000002cf19
Faulting process identifier: 0x88c
Faulting Application Start Time: 0x01d9ba664717b8bc
Faulting application path: D:\Applications\Simulation\Flight Simulation\FS2020\addons\EasyCPDLC\EasyCPDLC0.2.0.0\EasyCPDLC.exe
Faulting module path: C:\Windows\System32\KERNELBASE.dll
Report ID: 5d18bb01-dd6d-4c8b-95d8-da104a538f78
Full name of the package with errors:

Regards

**Comment by zalloon** [comment]
Hi there, same here. But I tried with compatibility mode on (Windows 8) and it worked... it needs a recompiling for the latest Windows version.
Good luck!
